name: Update readme

on:
  repository_dispatch:
    types: [update]

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(result)