name: Build readme

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch data from API
      uses: actions/github-script@v3
      id: fetch-data
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const { data: issues } = await github.issues.listForRepo({
            owner: 'lucas-lm', 
            repo: 'nowiknow' 
          })
          const learning = issues.map(issue => issue.title)
          return { learning }

    - name: Update data
      run: echo "${{steps.fetch-data.outputs.result}}" && echo "${{steps.fetch-data.outputs.result}}" >> data.json
      
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - run: yarn
    - run: yarn build
      env:
        CI: true
    
    - name: Push to remote
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git add -A
        git commit -m ":robot: update readme"
        git push